version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - docker login -u adam535 -p sozowater123
      - REPOSITORY_URI=466807463245.dkr.ecr.us-east-1.amazonaws.com/test-repo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ecr-test .
      - docker tag ecr-test:latest $REPOSITORY_URI:ecr-test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:ecr-test
